### ISSUE TITLE
Mobile input support

### ISSUE THREAD

**Issue by agoncharov-reef** [reef-technologies/xterm.js#1]
In order to disable any autocomplete/autocorrection on mobile, the only solution is to use `input type="password"`.
More on this here: https://github.com/xtermjs/xterm.js/issues/2403

In `frontend/node_modules/xterm/lib/xterm.js`, the textarea variable should be not `<textarea ...>`  but `<input type="password" autocomplete="nope" ...>`. All other properties like autocorrect etc should remain the same.
I achieved this by manually changing `xterm/lib/xterm.js` so that it contains this chunk:
```
this.textarea=T.createElement("input"),this.textarea.setAttribute("type", "password"),this.textarea.setAttribute("autocomplete", "nope")
```
This should definitely be done somewhere in TS, but I have no idea where exactly and how to compile TS etc and just don't want to waste time on it.

**Comment by testrocket** [comment]
I tried couple of other solutions (wrapping with form element or changing attributes dynamically etc.) but overall your is the only one that actually works properly.
It has one disadvantage - you can't copy text from input fields with type="password" attribute. Paste works as usual.
PR ready.

**Comment by testrocket** [comment]
Creating PR again - by mistake this PR was posted somewhere else...
